[PHP]
memory_limit = 1G
max_execution_time = 0
max_input_time = 300
default_socket_timeout = 300
date.timezone = Asia/Bangkok

opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 32
opcache.max_accelerated_files = 10000
opcache.validate_timestamps = 0
opcache.jit = 1254
opcache.jit_buffer_size = 128M

swoole.enable_coroutine = On
swoole.use_shortname = On

realpath_cache_size = 16M
realpath_cache_ttl = 3600

expose_php = Off
log_errors = On
display_errors = Off
